### PR TITLE
gds-replicating fastRP

### PR DESCRIPTION
**Pull request by AlfredClemedtson**

### CODE REVIEW

File: crates/algos/src/fast_rp_gds.rs [hunk 1]
```diff
@@ -0,0 +1,350 @@
...
+        Self {
+            out_dim: FastRPConfig::DEFAULT_OUT_DIM,
+            coefficients: FastRPConfig::DEFAULT_COEFFICIENTS.to_vec(),
+            normalization_strength: FastRPConfig::DEFAULT_NORMALIZATION_STRENGTH,
+            random_seed: FastRPConfig::DEFAULT_RANDOM_SEED,
+        }
+    }
+}
+
+struct RandomGenerator {
```
Comment (s1ck) [inline crates/algos/src/fast_rp_gds.rs]: I think it would be good to document this beast to make it clear that it's essentially mirroring the Java RNG and that we need this to align with GDS behaviour.

Comment (s1ck) [reply crates/algos/src/fast_rp_gds.rs]: Maybe instead of documenting just that RNG, it would be better to document the whole algo and also link to the Java impl on GitHub.

File: Cargo.toml [hunk 2]
```diff
@@ -43,14 +43,15 @@ num = "0.4.1"
...
+ndarray = "0.15.x" #must be same as numpy uses!
 page_size = "0.4.2"
 parking_lot = "0.12.1"
 pico-args = "0.5.0"
 polars = { version = "0.25.1", default_features = false, features = ["fmt"] }
 pyo3 = "0.17.3"
 pyo3-log = "0.7.0"
 rand = "0.8.5"
-rayon = "1.7.0"
+rayon = "1.7.0, <1.10.0"
```
Comment (s1ck) [inline Cargo.toml:54]: Why do we need this constraint?

File: crates/mate/graph_mate.pyi [hunk 3]
```diff
@@ -112,6 +112,10 @@ class DiGraph:
         self, *, chunk_size: int, neighbor_rounds: int, sampling_size: int
     ) -> WccResult:
         """Run Weakly Connected Components on this graph."""
+    def fast_rp(
```
Comment (s1ck) [inline crates/mate/graph_mate.pyi:115]: maybe also use the `_gds` suffix here to make this more clear?

File: crates/mate/tests/fast_rp_test.py [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+def test_coefficients(g: DiGraph):
+    pass
+
+
+def test_normalization_strength(g: DiGraph):
+    pass
+
+
+def test_random_seed(g: DiGraph):
+    pass
```
Comment (s1ck) [inline crates/mate/tests/fast_rp_test.py]: mh?

**Review by s1ck — COMMENTED** [review]
I like it and I am not against merging this and improving parallelism later. However, if it's not strictly necessary to mirror the exact GDS implementation, I'd prefer to do that instead.

Does mirroring GDS somehow limit you in terms of performance, e.g. the ability to parallelize more?

File: Cargo.toml (hunk 2 above)
Comment (AlfredClemedtson) [reply Cargo.toml:54]: Can't build with rayon 1.11. Looks like the builder crate needs <= 1.10.
```error[E0271]: type mismatch resolving `<IntoIter<(NI, NI, EV)> as ParallelIterator>::Item == &_`
   --> crates/builder/src/input/edgelist.rs:125:35
    |
125 |         self.list.into_par_iter().copied()
    |                                   ^^^^^^ expected `&_`, found `(NI, NI, EV)`
    |```
